# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'HeyPlay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for HeyPlay
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'FSPagerView'
  pod 'ViewPager-Swift'
  pod 'SwiftUI-Shimmer', :git => 'https://github.com/markiv/SwiftUI-Shimmer.git'
  pod 'ShimmerSwift'
  pod 'Alamofire', '5.9'
end
