# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'HeyPlay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HeyPlay
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'FSPagerView'
  pod 'ViewPager-Swift'
  pod 'SwiftUI-Shimmer', :git => 'https://github.com/markiv/SwiftUI-Shimmer.git'
  pod 'ShimmerSwift'
  pod 'Alamofire', '5.9'
  pod 'Wormholy', :configurations => ['Debug']
  pod 'GoogleSignIn'
  pod 'LineSDKSwift', '~> 5.0'
  pod 'FirebaseCore'
  pod 'FirebaseMessaging'
  pod 'Google-Mobile-Ads-SDK'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
